# Copyright (c) 2021 Veli Matti Lastumäki (Velsku at lampopumput.info),
#                    Joonas Ihonen (puu at lampopumput.info),
#                    Ilkka Roivainen (iro at lampopumput.info)
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


###########################################################################
##        Home Assistant and Logger settings                             ##
##        ----------------------------------------------------------     ##
###########################################################################
# Enable/disabe HomeAssistant
#api:                                       # !! If home Assistant in use remove comment (#)
#  reboot_timeout: $common_reboot_timeout   # !! If home Assistant in use remove comment (#)
#####################
# Select logger-level
logger:          #  After installation and testing phase it may be wise to reduce debug communication
  level: INFO    # by adding comment (#) at the begining of this line more log-info
#  baud_rate: 0   # USB-logs disabled

###########################################################################
##        This module specifies HW of your SonOff Elite Mitsurunner      ##
##        ----------------------------------------------------------     ##
##  ! updateIDs of your Dallas DS18B20 sensors                           ##
##  ! update used IO-pins                                                ##
##  hardware platform (preconfigured for SonOff)                         ##
##########################################################################

# Define these values according to your hardware see: https://esphome.io
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
  
###########################################################################
substitutions:

# Sw_version, Update !
  fw_version: "2026_1"  

# Common reboot timeout for WiFi, MQTT and HomeAssiant. Change value if needed.
  common_reboot_timeout: '600min'

# Addresses for your Dallas DS18B20 temperature sensors - you need to update these

  dallas_address_heat_exchanger_temp: '0x0000000000000000'
  dallas_address_outdoor_temp:        '0x0000000000000000'

# IO-pins:
  dallas_pin: 'GPIO25' # Pin for DS18B20 1-wire temperature sensors. Set to the pin number you are using.
  relay_pin: 'GPIO4' # Pin for controlling relay
  dallas_power_pin: 'GPIO27'

#############################################################################
#########################Sonoff Th Elite display#############################
###            two LCD screens alternate every 5 seconds                  ###
#############################################################################
###   heat_exchanger_temp  ###########  Wifi-signal        ##################
###   outdoor_temp         ###########  Dallas error count ##################
#############################################################################
### RED LED = POWER #### GREEN LED = Defrost prevention control activated ###
#############################################################################

switch:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: true
    internal: true
    id: red_led

output:
  - platform: gpio
    pin: GPIO13
    inverted: true
    id: green_led

  - platform: gpio
    pin: GPIO15
    inverted: true
    id: blue_led

##########################################################################

interval:
  - interval: 1000ms
    then:
      - lambda: |-

          if (id(gpio_relay).state) id(green_led).turn_on();    //Green LED ON if defrost_prevention_Relay is ON
            else id(green_led).turn_off();

          if (wifi::global_wifi_component->is_ap_active()) id(blue_led).turn_on();
            else id(blue_led).turn_off();

          if (wifi::global_wifi_component->is_connected()) {
            id(red_led).turn_on();       // when WiFi-connected ==>  red-led is ON
          } else {
            id(red_led).toggle();        // when WiFi is not connected ==> red-led blinks
          }

display:
  platform: tm1621
  id: tm1621_display
  update_interval: 2500ms
  cs_pin: GPIO17
  data_pin:
    number: GPIO5
    ignore_strapping_warning: true
  read_pin: GPIO23
  write_pin: GPIO18
  lambda: |-
    static int n = 0;
    
    n = n+1;   
    if ((n == 1) || (n == 2)|| (n == 4)|| (n == 5)) {
       it.printf(0, "%.1f", id(heat_exchanger_temp).state);
       it.display_celsius(true);
       it.printf(1, "%.1f", id(outdoor_temp).state);
       it.display_humidity(false);
       return;
       }
    if (n == 3) {
       it.printf(0,"%.1i", id(heat_exchanger_temp_errors));   
       it.display_celsius(false);
       it.printf(1,"%.1i", id(outdoor_temp_errors));
       it.display_humidity(false);
       return;
       }
    if (n == 6) {
       n = 0;
       it.printf(0, "%.1f", id(wifi_signal_dbm).state);
       it.display_celsius(false);
       it.printf(1,"%3.0f", id(ip_last).state);    
       it.display_humidity(false);
       }
    if (n == 6) {
       n = 0;
       it.printf(0, "%.5d", id(wifi_signal_dbm).state);
       it.display_celsius(false);
       it.printf(1,"%3.0f", id(ip_last).state);    
       it.display_humidity(false);
       }

##########################################################################
text_sensor:                ## last part of ip-address
  - platform: wifi_info
    ip_address:
      name: "IP-osoite"
      id: ip_address
      internal: true

  - platform: template   ## software version 
    name: "_Firmware version"
    icon: mdi:tag
    lambda: |-
      return {"${fw_version}"};

##########################################################################
sensor:
  - platform: template
    id: ip_last
    name: "IP loppuosa"
    internal: true
    lambda: |-
      if (id(ip_address).state == "") return NAN;
      int last = atoi(id(ip_address).state.substr(
        id(ip_address).state.find_last_of('.') + 1).c_str());
      return last;
    update_interval: 60s
    
########################################################################
